version: 2.1
jobs: 
  build:
    docker:
      - image: circleci/node:10-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
          
      - persist_to_workspace:
          root: .
          paths:
            - .
  
  run_tests:
    docker:
      - image: circleci/node:10-browsers
        environment:
          NODE_ENV: development

    steps:
     - attach_workspace:
         at: .
     - run: yarn start    
     - run: npx percy exec -- node tests/percy/homepage.js 

workflows:
 test:
   jobs:
     - build
     - run_tests:
         requires:
           - build